swagger: '2.0'
info:
  description: This a proposed API for the Verify Serivce Provider
  version: 0.3.0
  title: Verify Service Provider
basePath: /
tags:
- name: 'Verify Service Provider API'
paths:
  /generate-request:
    post:
      tags:
      - 'Verify Service Provider API'
      description: 'Generate an authn request'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: requestGenerationBody
          in: body
          required: true
          schema:
            $ref: '#/definitions/RequestGenerationBody'
      responses:
        200:
          description: An object containing a SAML request.
          schema:
            $ref: '#/definitions/RequestResponseBody'
        422:
          description: >-
            An error due to a JSON request in an invalid format (e.g. missing mandatory parameters).
          schema:
            $ref: '#/definitions/ErrorMessage'
          examples:
            'errorMessage':
              code: 422
              message: "Some error message"
        500:
          description: An error due to an internal server error.
          schema:
            $ref: '#/definitions/ErrorMessage'
          examples:
            'errorMessage':
              code: 500
              message: "Some error message"
  /translate-response:
    post:
      tags:
      - 'Verify Service Provider API'
      description: 'Create a translated response'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: responseBody
          description: An object containing a details of a SAML Authn response.
          in: body
          required: true
          schema:
            $ref: '#/definitions/TranslateSamlResponseBody'
      responses:
        200:
          description: >-
            Response contains an object with details of a translated SAML
            response.
          schema:
            $ref: '#/definitions/TranslatedResponseBody'
        400:
          description: an error due to a problem with translating the Response
          schema:
            $ref: '#/definitions/ErrorMessage'
          examples:
            'errorMessage':
              code: 400
              message: "Some error message"
        422:
          description: An error due to a JSON request in an invalid format (e.g. missing mandatory parameters).
          schema:
            $ref: '#/definitions/ErrorMessage'
          examples:
            'errorMessage':
              code: 422
              message: "Some error message"
        500:
          description: an error due to an internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'
          examples:
            'errorMessage':
              code: 500
              message: "Some error message"
definitions:
  ExpectedLevelOfAssurance:
    description: Level of assurance requested by the Service
    type: string
    enum:
      - LEVEL_1
      - LEVEL_2
  ReceivedLevelOfAssurance:
    description: Level of assurance the user authenticated with.
    type: string
    enum:
      - LEVEL_1
      - LEVEL_2
  Scenario:
      type: string
      enum:
        - SUCCESS_MATCH
        - ACCOUNT_CREATION
        - NO_MATCH
        - CANCELLATION
        - AUTHENTICATION_FAILED
        - REQUEST_ERROR
  RequestGenerationBody:
    type: object
    properties:
      levelOfAssurance:
        $ref: '#/definitions/ExpectedLevelOfAssurance'
      entityId:
        description: >-
          The Entity Id for the service interacting with the Verify Service Provider.
          This is required if the Verify Service Provider is set up for multi-tenanted
          use, otherwise it is optional. The value, if provided, must be one of those
          listed in the configuration for the Verify Service Provider.
        type: string
  RequestResponseBody:
    type: object
    required:
      - samlRequest
      - requestId
      - ssoLocation
    properties:
      samlRequest:
        description: SAML authn request string as a base64 string
        type: string
        format: byte
      requestId:
        description: >-
          A token that identifies the authn request. This can be used to later
          verify that the request and response have passed through the same
          browser.
        type: string
        format: byte
      ssoLocation:
        description: The url for Verify HUB SSO. The entrypoint for saml authn flow.
        type: string
        format: url
  TranslateSamlResponseBody:
    type: object
    required:
      - samlResponse
      - requestId
      - levelOfAssurance
    properties:
      samlResponse:
        description: A SAML Authn response as a base64 string.
        type: string
        format: byte
      requestId:
        description: >-
          A token that was generated for the original SAML Authn request. The
          token is used to verify that the request and response are from the
          same browser.
        type: string
        format: byte
      levelOfAssurance:
        description: The minimum level of assurance required
        $ref: '#/definitions/ReceivedLevelOfAssurance'
      entityId:
        description: >-
          The Entity Id for the service interacting with the Verify Service Provider.
          This is required if the Verify Service Provider is set up for multi-tenanted
          use, otherwise it is optional. The value, if provided, must be one of those
          listed in the configuration for the Verify Service Provider.
        type: string
  TranslatedResponseBody:
    type: object
    required:
      - scenario
      - pid
    properties:
      scenario:
        $ref: '#/definitions/Scenario'
      pid:
        description: >-
          A unique identifier that can identify a user against an internal
          record.
        type: string
        format: byte
      levelOfAssurance:
        $ref: '#/definitions/ReceivedLevelOfAssurance'
      attributes:
        description: An optional attributes-object if no match was possible
        $ref: '#/definitions/Attributes'
  ErrorMessage:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: number
      message:
        type: string
  Attributes:
    description: >-
      An object containing user attributes
    type: object
    properties:
      firstName:
        type: object
        properties:
          value:
            type: string
          verified:
            type: boolean
      middleName:
        type: object
        properties:
          value:
            type: string
          verified:
            type: boolean
      surname:
        type: object
        properties:
          value:
            type: string
          verified:
            type: boolean
      dateOfBirth:
        type: object
        properties:
          value:
            description: Format yyyy-MM-dd
            type: string
          verified:
            type: boolean
      address:
        type: object
        properties:
          value:
            $ref: '#/definitions/Address'
          verified:
            type: boolean
      cycle3:
        type: string
  Address:
    description: >-
      An object describing the address fields of a user
    type: object
    properties:
      lines:
        type: array
        items:
          type: string
      postCode:
        type: string
      internationalPostCode:
        type: string
      uprn:
        type: string
      fromDate:
        description: Format yyyy-MM-dd
        type: string
      toDate:
        description: Format yyyy-MM-dd
        type: string
